# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - uacloudaction356

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_dfc9a62a0dcd4534b23653fd04088801 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb70e65f0e1c468bb31de5ab48424b80 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_dfc9a62a0dcd4534b23653fd04088801 }}/uaclac4324fassfer90324rqfafrer34:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'uacloudaction356'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c2c19d56ea544d969f980520ebea72d8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_dfc9a62a0dcd4534b23653fd04088801 }}/uaclac4324fassfer90324rqfafrer34:${{ github.sha }}'