# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - uacloudaction356

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_14808d380be74d6ca7d2473f40a2277f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_37fcbf86319d4449abe0e688ef6bbedf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_14808d380be74d6ca7d2473f40a2277f }}/uaclac4324fassfer90324rqfafrer34:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'uacloudaction356'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_587a30e8b7da469ba50814561b7895d5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_14808d380be74d6ca7d2473f40a2277f }}/uaclac4324fassfer90324rqfafrer34:${{ github.sha }}'